### PR TITLE
feat/(matches-page-create-team-and-NF-ID)

### PR DESCRIPTION
**Pull request by Alishan112**
# Merge Request: Enhance User Experience and Functionality

## Description
This merge request introduces several key features and improvements aimed at enhancing user experience and functionality within the application.

## Work List
- **Make Matches Page Dynamic:**  
  Updated the matches page to pull data dynamically from the backend.

- **Allow User to Create Team:**  
  Implemented functionality for users to create and manage their own teams.

- **Show Upcoming and Completed Matches on Home Page:**  
  Enhanced the homepage to display both upcoming and completed matches.

- **Add NF-ID Option to Authenticate User:**  
  Integrated a NF-ID option for user authentication, enabling a seamless login experience.

## Checklist
- [x] Code follows coding standards
- [ ] Documentation updated
- [ ] Tests added/updated
- [ ] All tests passed

## Additional Notes
(Any other relevant information or context.)

### CODE REVIEW

**Comment by Hafiz-Abdullah-Umar** [comment]
@Alishan112 add .dfx to gitignore

**Comment by Alishan112** [comment]
> @Alishan112 add .dfx to gitignore

@Hafiz-Abdullah-Umar  removed .dfx folder

**Comment by Hafiz-Abdullah-Umar** [comment]
@istiwanaayesha pr is aproved

**Review by Hafiz-Abdullah-Umar — APPROVED** [review]
@istiwanaayesha pr is approved

**Pull request merged**
